name: no-blank-issue
description: >
  Closes newly opened issues that have no labels, indicating that the issue
  forms have not been used.
author: ldez
branding:
  icon: tag
  color: red

inputs:
  github-token:
    description: GitHub token for API calls.
    required: true
    default: ${{ github.token }}

runs:
  using: node24
  main: dist/index.js
